const OFFICIAL_LINCO_DEMO_WS_BASE_URL = 'ws://127.0.0.1:3300/bridge/ws';

const OFFICIAL_LINCO_DEMO_AGENT_WS_URLS = {
  claude: `${OFFICIAL_LINCO_DEMO_WS_BASE_URL}/claude`,
  codex: `${OFFICIAL_LINCO_DEMO_WS_BASE_URL}/codex`,
  hermes: `${OFFICIAL_LINCO_DEMO_WS_BASE_URL}/hermes`,
  openclaw: `${OFFICIAL_LINCO_DEMO_WS_BASE_URL}/openclaw`,
};

const DEFAULT_LINCO_DEMO_WS_URL = OFFICIAL_LINCO_DEMO_AGENT_WS_URLS.claude;

module.exports = {
  DEFAULT_LINCO_DEMO_WS_URL,
  OFFICIAL_LINCO_DEMO_AGENT_WS_URLS,
  OFFICIAL_LINCO_DEMO_WS_BASE_URL,
};
